import { Section } from './custom_pages/types/sections';

export const INITIAL_SECTIONS: Section[] = [
  {
    id: 'hero-slider',
    type: 'slider',
    visible: true,
    enableSpeech: false,
    enableTitleSpeech: false,
    enableDescriptionSpeech: false,
    slides: [],
    autoplay: false,
    autoplayDelay: 3000,
    showNavigation: true,
    showPagination: true,
    effect: 'slide',
    loop: false,
    height: '400px',
    width: '100%',
  },
  {
    id: 'hero',
    type: 'hero',
    visible: true,
    enableSpeech: false,
    enableTitleSpeech: false,
    enableDescriptionSpeech: false,
    title: 'Welcome to My Portfolio',
    description: 'Professional Web Developer & Designer',
    backgroundMedia: '/placeholder.svg?height=1080&width=1920',
    mediaType: 'image',
    height: 'h-[40vh] min-h-[300px] max-h-[400px]',
    width: 'w-full',
    objectFit: 'cover' as const,
    objectPosition: 'center' as const,
    maxHeight: 400,
  },
  {
    id: 'about-section',
    type: 'media-text-left' as const,
    visible: true,
    enableSpeech: false,
    title: 'About Me',
    description: 'Add your about content here',
    mediaUrl: '/placeholder.svg?height=400&width=400',
    mediaType: 'image' as const,
    mediaPosition: 'left' as const,
    enableTitleSpeech: false,
    enableDescriptionSpeech: false,
  },
  {
    id: 'content-previews-section',
    type: 'feature-card-grid' as const,
    visible: true,
    enableSpeech: false,
    numCards: 3,
    cards: [
      {
        id: 'free-content',
        mediaUrl: '/placeholder.svg?height=300&width=400',
        mediaType: 'image' as const,
        title: 'Free Content',
        description: 'Check out our free content',
        ctaText: 'View Free',
        ctaUrl: '#free',
        ctaOpenInNewTab: false,
      },
      {
        id: 'premium-content',
        mediaUrl: '/placeholder.svg?height=300&width=400',
        mediaType: 'image' as const,
        title: 'Premium Content',
        description: 'Upgrade for premium content',
        ctaText: 'Upgrade Now',
        ctaUrl: '#premium',
        ctaOpenInNewTab: false,
      },
      {
        id: 'vip-content',
        mediaUrl: '/placeholder.svg?height=300&width=400',
        mediaType: 'image' as const,
        title: 'VIP Content',
        description: 'Exclusive VIP content',
        ctaText: 'Become VIP',
        ctaUrl: '#vip',
        ctaOpenInNewTab: false,
      },
    ],
  },
];
